/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-cascade_custom_bike-an6vWSCQtmStpfeS-vsFJhN2oMsNTuz-",
  "version": "2020-11-20"
}

export default ebconfig;